server.port=8082
spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://postgres:5432/databass
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

jwt.key=${JWT_SECRET_KEY}